version: '3'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/usr/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db

volumes:
  db-data:
    driver: local
